import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
const OUT='/tmp/';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await b.newContext({viewport:{width:400,height:800},deviceScaleFactor:1});
const pg=await ctx.newPage();
const errs=[];pg.on('pageerror',e=>errs.push('pageerror: '+e.message));pg.on('console',m=>{if(m.type()==='error')errs.push('console: '+m.text())});
const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m);if(!c)process.exitCode=1};
const wait=ms=>pg.waitForTimeout(ms);
await pg.goto('http://localhost:8765/index.html');
await pg.click('[data-a="formset"][data-v="dev"]');
for(const [k,v] of [['nome','Mario'],['cognome','Rossi'],['username','mario'],['pw','password123'],['pw2','password123']])await pg.fill(`input[data-k="${k}"]`,v);
await pg.click('[data-a="setupGo"]');
await pg.waitForSelector('.testbar');
await pg.click('[data-a="viewAs"][data-v="staff"]');await wait(400);
ok(await pg.evaluate(()=>document.documentElement.classList.contains('staff-ui')),'staff-ui class on staff view');
ok(await pg.locator('.steps3').count()===1,'3-step hint shown');
ok(await pg.locator('#results .sup').count()===0,'no supplier names in staff catalog');
const t0=await pg.locator('#results .sec').innerText();ok(t0==='Tutti i prodotti','default title before any request: '+t0);
await pg.screenshot({path:OUT+'ta1.png'});
// search zucchero -> one row, + adds cheapest (dolpa demo02)
await pg.fill('#q','zucchero');await wait(200);
ok(await pg.locator('#results .pg').count()===1,'zucchero: one row');
await pg.click('#results .add');await wait(200);
let cart=await pg.evaluate(()=>S.cart.map(c=>c.pid));ok(cart.join()==='demo02','zucchero default = cheapest (demo02): '+cart);
ok(await pg.locator('#results .step').count()===1,'stepper shown after add');
await pg.click('#results .step button[data-d="1"]');await wait(100);
ok(await pg.evaluate(()=>S.cart[0].qta)===2,'stepper + increments');
await pg.fill('#q','cozze');await wait(200);
await pg.click('#results .add');await wait(200);
cart=await pg.evaluate(()=>S.cart.map(c=>c.pid));ok(cart.join()==='demo02,demo07','cozze default = cheapest (demo07): '+cart);
// free text item
await pg.fill('#q','lievito di birra');await wait(200);
await pg.click('[data-a="cfree"]');await wait(200);
const bar=pg.locator('.cartbar .btn');
ok(await bar.count()===1,'cart bar visible');
ok((await bar.innerText()).includes('3 articoli · Invia allo chef'),'cart bar text: '+(await bar.innerText()));
const bb=await bar.boundingBox(),nb=await pg.locator('.nav').boundingBox();
ok(bb.y+bb.height<=nb.y+1,`bar above nav (bar bottom ${bb.y+bb.height}, nav top ${nb.y})`);
const pb=await pg.evaluate(()=>getComputedStyle(document.querySelector('.main')).paddingBottom);ok(parseFloat(pb)>=180,'main bottom padding '+pb);
await pg.fill('#q','');await wait(150);
await pg.screenshot({path:OUT+'ta2.png'});
await pg.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));await wait(150);
await pg.screenshot({path:OUT+'ta2b.png'});
// other staff tabs show the bar too
await pg.click('.nav [data-v="miei"]');await wait(150);ok(await pg.locator('.cartbar').count()===1,'bar on I miei ordini');
await bar.click();await wait(200);
ok(await pg.evaluate(()=>S.tab)==='carrello','bar opens cart');
ok(await pg.locator('.cartbar').count()===0,'no bar in cart');
ok(await pg.locator('#app .fsec-h').count()===0,'cart: no supplier headers for staff');
await pg.screenshot({path:OUT+'ta3.png'});
await pg.click('[data-a="csend"]');await wait(500);
ok(await pg.locator('.sheet .done').count()===1,'first send ok, no dup alert');
await pg.click('.sheet [data-a="closeSheet"].btn');await wait(400);
await pg.click('.nav [data-v="catalogo"]');await wait(200);
const t1=await pg.locator('#results .sec').innerText();ok(t1==='I tuoi soliti','title now: '+t1);
ok(await pg.locator('#results .pg').count()===2,'soliti rows: '+await pg.locator('#results .pg').count());
// add zucchero again from soliti and send -> duplicate alert, cancel first
await pg.locator('#results .pg',{hasText:'Zucchero'}).locator('.add').click();await wait(150);
await pg.locator('.cartbar .btn').click();await wait(200);
await pg.click('[data-a="csend"]');await wait(500);
const st=await pg.locator('.sheet .sh-t').innerText();ok(st==='Attenzione: già richiesto','ask title: '+st);
const txt=await pg.locator('.sheet p.muted').innerText();console.log('  ask text:',JSON.stringify(txt));
ok(/Zucchero semolato 1 kg: chiesto da te oggi alle \d\d:\d\d/.test(txt)&&txt.includes('È corretto inviarlo di nuovo?'),'ask text lists duplicate');
await pg.screenshot({path:OUT+'ta4.png'});
const nReq0=await pg.evaluate(()=>Object.keys(S.data.richieste).length);
await pg.click('.sheet .btn.ghost[data-a="closeSheet"]');await wait(400);
ok(await pg.evaluate(()=>Object.keys(S.data.richieste).length)===nReq0,'cancel: nothing sent');
ok(await pg.evaluate(()=>S.cart.length)===1,'cancel: cart kept');
await pg.click('[data-a="csend"]');await wait(500);
await pg.click('#ask-ok');await wait(600);
ok(await pg.locator('.sheet .done').count()===1,'confirmed send ok');
const last=await pg.evaluate(()=>Object.values(S.data.richieste).sort((a,b)=>b.creato-a.creato)[0]);
ok(Array.isArray(last.doppi)&&last.doppi.length===1&&last.doppi[0].nome==='Zucchero semolato 1 kg'&&last.doppi[0].da==='Mario Rossi'&&typeof last.doppi[0].quando==='number','doppi saved: '+JSON.stringify(last.doppi));
const nt=await pg.evaluate(()=>Object.values(S.data.notifiche).filter(n=>n.a==='gm').sort((a,b)=>b.creato-a.creato)[0].testo);
ok(nt.endsWith('(possibile doppione)'),'chef notification: '+nt);
await pg.click('.sheet [data-a="closeSheet"].btn');await wait(400);
// free-text duplicate
await pg.click('.nav [data-v="catalogo"]');await wait(200);
await pg.fill('#q','Lievito di Birra');await wait(150);await pg.click('[data-a="cfree"]');await wait(150);
await pg.locator('.cartbar .btn').click();await wait(200);await pg.click('[data-a="csend"]');await wait(500);
const txt2=await pg.locator('.sheet p.muted').innerText();ok(txt2.includes('Lievito di Birra: chiesto da te'),'free-text dup detected: '+JSON.stringify(txt2.split('\n')[0]));
await pg.click('#ask-ok');await wait(600);await pg.click('.sheet [data-a="closeSheet"].btn');await wait(400);
// chef view
await pg.click('[data-a="viewAs"][data-v="gm"]');await wait(400);
ok(await pg.evaluate(()=>!document.documentElement.classList.contains('staff-ui')),'no staff-ui for chef');
ok(await pg.locator('.cartbar').count()===0,'no cart bar for chef');
const nb2=await pg.locator('.banner.dup').count();ok(nb2===2,'chef sees dup banners: '+nb2);
console.log('  banner:',JSON.stringify(await pg.locator('.banner.dup').first().innerText()));
ok(await pg.locator('select[data-ch="rswap"]').count()>=1,'chef can swap supplier (rswap select present)');
const opts=await pg.locator('select[data-ch="rswap"]').first().locator('option').allInnerTexts();console.log('  swap options:',opts);
await pg.screenshot({path:OUT+'ta5.png',fullPage:true});
// desktop width, staff with cart
await pg.click('[data-a="viewAs"][data-v="staff"]');await wait(300);
const firstT=await pg.locator('#results .pg-t').allInnerTexts();ok(firstT[0]==='Zucchero semolato 1 kg'&&firstT[1].startsWith('Cozze'),'soliti sorted by frequency: '+firstT);
await pg.fill('#q','arselle');await wait(150);await pg.click('#results .add');await wait(150);await pg.fill('#q','');await wait(100);
await pg.setViewportSize({width:1280,height:800});await wait(300);
const db=await pg.locator('.cartbar .btn').boundingBox(),mb=await pg.locator('.main').boundingBox(),nv=await pg.locator('.nav').boundingBox();
ok(db.x>=nv.x+nv.width&&Math.abs((db.x+db.width/2)-(mb.x+mb.width/2))<2,`desktop bar centered on main (bar ${Math.round(db.x)}-${Math.round(db.x+db.width)}, main ${Math.round(mb.x)}-${Math.round(mb.x+mb.width)})`);
await pg.screenshot({path:OUT+'ta6.png'});
await pg.click('.cartbar .btn');await wait(200);await pg.screenshot({path:OUT+'ta7.png'});
await pg.setViewportSize({width:400,height:800});await wait(300);
await pg.screenshot({path:OUT+'ta8.png'});
ok(errs.filter(e=>e.startsWith("pageerror")).length===0,"no pageerror: "+JSON.stringify(errs));
await b.close();
